# XaruChallenges Configuration
# Database Settings
database:
  enabled: true
  type: SQLite
  sqlite:
    filename: challenges.db
  mysql:
    host: localhost
    port: 3306
    database: minecraft
    username: user
    password: pass

# General Settings - if its se to 'true', only operators are allowed to add or remove challenges
op-management: true

# Challenge Configurations
Piranha:
  damage-outside-water: 2.0
  allow-vehicles: false
  underwater-effect: WATER_BREATHING
  disallowed-food:
    - COD
    - COOKED_COD
    - SALMON
    - COOKED_SALMON
    - TROPICAL_FISH
    - PUFFERFISH
    - DRIED_KELP
    - KELP
  allowed-food: []

Vampire:
  damage-in-sunlight: 1.0
  light-level-threshold: 12

Daredevil:
  blindness-effect: true

HollowBones:
  max-health: 2

CaseOh:
  sprint-disabled: true

Chinchilla:
  water-death: true
  allowed-food:
    - COD
    - COOKED_COD
    - SALMON
    - COOKED_SALMON
    - TROPICAL_FISH
    - PUFFERFISH

Prasinophobia:
  disallowed-blocks:
    - GRASS_BLOCK
    - TALL_GRASS
    - LEAVES
    - VINE

Mole:
  allowed-blocks:
    - DIRT
    - COARSE_DIRT
    - SAND

OreDeath:
  #Ores that kill the player if he touches it
  ore-list:
    - IRON_ORE
    - RAW_IRON
    - DEEPSLATE_IRON_ORE
    - RAW_IRON_BLOCK
    - IRON_BLOCK
    - IRON_INGOT
    - IRON_NUGGET
    - GOLD_ORE
    - RAW_GOLD
    - DEEPSLATE_GOLD_ORE
    - RAW_GOLD_BLOCK
    - GOLD_BLOCK
    - GOLD_INGOT
    - NETHER_GOLD_ORE
    - GOLD_NUGGET
    - ANCIENT_DEBRIS
    - NETHERITE_INGOT
    - DIAMOND_ORE
    - DIAMOND
    - DEEPSLATE_DIAMOND_ORE
    - EMERALD_ORE
    - EMERALD
    - DEEPSLATE_DIAMOND_ORE
    - COPPER_ORE
    - RAW_COPPER_INGOT
    - COPPER_INGOT
    - REDSTONE_ORE
    - REDSTONE_BLOCK
    - LAPIS_ORE
    - LAPIS_BLOCK
    - LAPIS_LAZULI
    - DEEPSLATE_LAPIS_ORE

Vegan:
  disallowed-food:
    - BEEF
    - COOKED_BEEF
    - CHICKEN
    - COOKED_CHICKEN
    - PORKCHOP
    - COOKED_PORKCHOP
    - MUTTON
    - COOKED_MUTTON
    - RABBIT
    - COOKED_RABBIT
    - COD
    - COOKED_COD
    - SALMON
    - COOKED_SALMON
  divine-punishment:
    lightning-strikes: 30

Vulture:
  allowed-food: ROTTEN_FLESH

NakedAndAfraid:
  armor-disabled: true
  drop-equipped-armor: true

Elf:
  allowed-weapons:
    - BOW
    - CROSSBOW